name: CI_CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "24"
jobs:
  testing-lint-nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-dependency-directory: package-lock.json

      - name: linting
        run: npm run lint

      - name: test
        run: npm run test
